insert into tags (tag_name) values ('Популярное');
insert into tags (tag_name) values ('Рекомендуемое');
insert into tags (tag_name) values ('Распродажа');
insert into tags (tag_name) values ('Для ценителей прекрасного');
insert into tags (tag_name) values ('Практичный товар');
insert into tags (tag_name) values ('Для детей');
insert into tags (tag_name) values ('Для взрослых');
insert into tags (tag_name) values ('Для компании друзей');
insert into tags (tag_name) values ('Новый год');
insert into tags (tag_name) values ('8 марта');
insert into tags (tag_name) values ('День рождения бабушки');
insert into tags (tag_name) values ('Для женатых');
insert into tags (tag_name) values ('Разбитое сердце');
insert into tags (tag_name) values ('Счастливый брак');
insert into tags (tag_name) values ('Джить до рассвета');
insert into tags (tag_name) values ('Экзистенциальный кризис');
insert into tags (tag_name) values ('Совершенный дух');
insert into tags (tag_name) values ('Совершенное тело');
insert into tags (tag_name) values ('Мотивация');
insert into tags (tag_name) values ('Дружба с внутренним ребенком');
